"""Cria tabela de cidades

Revision ID: f703cf036c21
Revises: 
Create Date: 2025-07-10 02:55:46.391368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f703cf036c21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cidades_id'), 'cidades', ['id'], unique=False)
    op.create_index(op.f('ix_cidades_nome'), 'cidades', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cidades_nome'), table_name='cidades')
    op.drop_index(op.f('ix_cidades_id'), table_name='cidades')
    op.drop_table('cidades')
    # ### end Alembic commands ###
